model = "gpt-5.3-codex"
model_reasoning_effort = "high"
tool_output_token_limit = 25000
model_auto_compact_token_limit = 233000
suppress_unstable_features_warning = true
web_search = "cached"
dangerouslyAllowAll = true

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[features]
collab = true
apps = true
ghost_commit = false
unified_exec = true
apply_patch_freeform = true
skills = true
shell_snapshot = true

[projects."/Users/kishore/code"]
trust_level = "trusted"

[projects."/Users/kishore/code/process/e2e-logging-platform"]
trust_level = "trusted"

[projects."/Users/kishore/Projects/skills"]
trust_level = "trusted"

[projects."/Users/kishore/Projects/ai-jumpstart"]
trust_level = "trusted"

[projects."/Users/kishore/Projects/sre/e2e-logging-platform"]
trust_level = "trusted"

[projects."/Users/kishore/Projects/e2e-marketplace"]
trust_level = "trusted"

[projects."/Users/kishore/Projects/awakening"]
trust_level = "trusted"
